[project]
name = "mle-model-deployment-project"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "click>=8.5.0",
    "fastapi>=0.141.1",
    "great-expectations>=1.23.1",
    "matplotlib>=3.11.2",
    "mlflow>=3.16.1",
    "numpy>=2.5.3",
    "optuna>=5.0.0",
    "pandas>=3.0.6",
    "plotly>=7.1.0",
    "pyarrow>=25.0.1",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
    "scikit-learn>=1.9.1",
    "seaborn>=0.13.2",
    "skops>=0.16.0",
    "uvicorn[standard]>=0.54.0",
]

[dependency-groups]
dev = [
    "httpx2>=2.13.1",
    "ipykernel>=7.3.0",
    "ipywidgets>=8.1.9",
    "nbformat>=5.11.1",
    "pytest>=9.1.1",
]
